[icons]
name = "awesome5"

[theme]
name = "nord-dark"

[[block]]
block = "custom"
interval = 1
command = "xdotool getwindowfocus getwindowname"
[block.theme_overrides]
idle_bg = "#2E3440" # nord0
idle_fg = "#B48EAD" # light blue

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "system up to date"

[[block]]
block = "custom"
command = "ibus engine"
interval = 10

[[block]]
block = "bluetooth"
mac = "FC:A8:9A:79:2C:F0"
format = "JBL HeadSet"
hide_disconnected = true

[[block]]
block = "bluetooth"
mac = "28:F0:33:A6:9E:5D"
format = "AirPods Pro"
hide_disconnected = true

[[block]]
block = "bluetooth"
mac = "D8:37:3B:58:F2:57"
format = "JBL Extreme"
hide_disconnected = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
[block.theme_overrides]
idle_bg = "#a3be8c" # nord0
idle_fg = "#2e3440" # light blue


[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
[block.theme_overrides]
idle_bg = "#a3be8c" # nord0
idle_fg = "#2e3440" # light blue

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#a3be8c" # nord0
idle_fg = "#2e3440" # light blue


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
[block.theme_overrides]
idle_bg = "#8fbcbb" # nord0
idle_fg = "#2e3440" # light blue


[[block]]
block = "sound"
driver="pulseaudio"
[block.theme_overrides]
idle_bg = "#ebcb8b" # nord0
idle_fg = "#2e3440" # light blue


[[block]]
block = "custom"
command = "whoami"
interval = "once"
[block.theme_overrides]
idle_bg = "#bf616a" # nord0
idle_fg = "#2e3440" # light blue

